### ISSUE TITLE
Problems with unbound_forward_zones

### ISSUE THREAD

**Issue by quulah** [Anthony25/ansible-role-unbound#3]
If using Python 3 (like on Ubuntu 18.04), you encounter this:

```
FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"}
```

`.iteritems()` has been removed in Python 3

Secondly, it's a dict so you can't have multiple keys with the same name, like in the case of multiple `forward-addr` keywords.

```
 [WARNING]: While constructing a mapping from ..., line 68, column 9, found a duplicate dict key (forward-addr). Using last defined value only.
```

**Comment by quulah** [comment]
Seems to be the same for stub-zones.

**Comment by Anthony25** [comment]
Hi,
Thanks for the issue. You're right about both, I will move to a list for `unbound_forward_zones` (but still supporting dicts for backward compatibility, just moving to `.items()` instead of `iteritems()`.

**Comment by Anthony25** [comment]
Hi @quulah,
Sorry for the delay. In fact, I kept dicts for forward and stub zones, but I switched to `items()` to fix the issue with python 3, and now allows to have a list as a value for one key in order to duplicate the option.

So, in your case, with multiple forward-addr, you can just do:
```
unbound_forward_zones:
  - name: domain.tld
    forward-addr:
      - addr1
      - addr2
```

Tell me if you have any issue with these changes.
Thanks!
